package vista;

import com.fazecast.jSerialComm.SerialPort;
import controlador.Lectura;
import controlador.Operacion;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.Estudiante;

/**
 *
 * @author Roycer
 */
public class Administracion extends javax.swing.JFrame {

    private Boolean AC;
    private Lectura lecturaPuerto;
    private Operacion opera = new Operacion();
    Estudiante estudiante = new Estudiante();
    
    public Administracion() {
        initComponents();
        AC = true;
        for(SerialPort i : SerialPort.getCommPorts()){
            jComboBox_Puertos.addItem(i.getSystemPortName());
        }
    }

    public void respuesta(String numeroTarjeta){
        jTextField_Tarjeta.setText(numeroTarjeta);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_AC = new javax.swing.ButtonGroup();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton_A = new javax.swing.JRadioButton();
        jRadioButton_B = new javax.swing.JRadioButton();
        jTextField_Tarjeta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jComboBox_Puertos = new javax.swing.JComboBox<>();
        jButton_Leer = new javax.swing.JButton();
        jTextField_Apellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_DNI = new javax.swing.JTextField();
        jLabel_Foto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_Examinar = new javax.swing.JButton();
        jTextField_Escuela = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_CUI = new javax.swing.JTextField();
        jButton_Cargar = new javax.swing.JButton();
        jTextField_Celular = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRACION");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup_AC.add(jRadioButton_A);
        jRadioButton_A.setSelected(true);
        jRadioButton_A.setText("Crear Usuario");
        jRadioButton_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_AActionPerformed(evt);
            }
        });

        buttonGroup_AC.add(jRadioButton_B);
        jRadioButton_B.setText("Editar Usuario");
        jRadioButton_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_BActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero de Tarjeta");

        jComboBox_Puertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PuertosActionPerformed(evt);
            }
        });

        jButton_Leer.setText("Cargar Datos de Usuario");
        jButton_Leer.setEnabled(false);
        jButton_Leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LeerActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("DNI");

        jLabel_Foto.setMaximumSize(new java.awt.Dimension(2, 2));
        jLabel_Foto.setMinimumSize(new java.awt.Dimension(2, 2));
        jLabel_Foto.setOpaque(true);

        jLabel6.setText("Seleccione puerto del dispositivo");

        jLabel5.setText("Escuela");

        jButton_Examinar.setText("Examinar");
        jButton_Examinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExaminarActionPerformed(evt);
            }
        });

        jLabel7.setText("CUI");

        jButton_Cargar.setText("Cargar");
        jButton_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CargarActionPerformed(evt);
            }
        });

        jLabel9.setText("Celular");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(jTextField_Tarjeta)
                                .addComponent(jButton_Leer, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(jComboBox_Puertos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(jTextField_Apellido)
                                .addComponent(jTextField_Nombre)
                                .addComponent(jTextField_DNI)
                                .addComponent(jTextField_Escuela))
                            .addComponent(jLabel5))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField_CUI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jButton_Examinar)))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jButton_Cargar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton_A)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_B)
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox_Puertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Leer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(jTextField_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Escuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Examinar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_CUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton_Cargar)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CargarActionPerformed
        // TODO add your handling code here:
        
        estudiante.setTarjeta(jTextField_Tarjeta.getText());
        estudiante.setNombre(jTextField_Nombre.getText());
        estudiante.setApellido(jTextField_Apellido.getText());
        estudiante.setCui(jTextField_CUI.getText());
        estudiante.setDni(jTextField_DNI.getText());
        estudiante.setEscuela(jTextField_Escuela.getText());
        estudiante.setCelular(jTextField_Celular.getText());
        try {
            if(AC){
                opera.crearEstudiante(estudiante);
            }else{
                opera.actualizarEstudiante(estudiante);
            }
            JOptionPane.showMessageDialog(this, "Operacion Exitosa");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo realizar la operacion.", "Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton_CargarActionPerformed

    private void jComboBox_PuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PuertosActionPerformed
        try {
            lecturaPuerto.cerrarPuerto();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        lecturaPuerto = new Lectura(jComboBox_Puertos.getSelectedItem().toString(),this);
        lecturaPuerto.start();
    }//GEN-LAST:event_jComboBox_PuertosActionPerformed

    private void jRadioButton_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_BActionPerformed
        AC=false;
        jButton_Leer.setEnabled(!AC);
    }//GEN-LAST:event_jRadioButton_BActionPerformed

    private void jRadioButton_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_AActionPerformed
        AC=true;
        jButton_Leer.setEnabled(!AC);
    }//GEN-LAST:event_jRadioButton_AActionPerformed

    private void jButton_ExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExaminarActionPerformed
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("Formatos de archivos(*.JPG;+.JPEG)","jpg","jpég");
        JFileChooser archivo=new JFileChooser();
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");    
        File ruta=new File("C:/Users/User/Pictures");
        archivo.setCurrentDirectory(ruta);
        int ventana=archivo.showOpenDialog(null);
        if(ventana == JFileChooser.APPROVE_OPTION)
        {
            File file=archivo.getSelectedFile();
            try {
                byte[] fileContent = Files.readAllBytes(file.toPath());
                estudiante.setFoto(fileContent);
                System.out.println(file.toPath());
            } catch (IOException ex) {
                Logger.getLogger(Administracion.class.getName()).log(Level.SEVERE, null, ex);
            }
            Image foto=getToolkit().getImage(String.valueOf(file));
            foto=foto.getScaledInstance(150, 150, Image.SCALE_DEFAULT);
            jLabel_Foto.setIcon(new ImageIcon(foto));
    
        }
    }//GEN-LAST:event_jButton_ExaminarActionPerformed

    private void jButton_LeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LeerActionPerformed
        if(!AC){
            estudiante = opera.buscarEstudiante(jTextField_Tarjeta.getText());
            if(estudiante != null){
                jTextField_Nombre.setText(estudiante.getNombre());
                jTextField_Apellido.setText(estudiante.getApellido());
                jTextField_Escuela.setText(estudiante.getEscuela());
                jTextField_DNI.setText(estudiante.getDni());
                jTextField_CUI.setText(estudiante.getCui());
                jTextField_Celular.setText(estudiante.getCelular()); 
                try {
                    jLabel_Foto.setIcon(opera.convBytetoImagenIcon(estudiante.getFoto()));
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton_LeerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_AC;
    private javax.swing.JButton jButton_Cargar;
    private javax.swing.JButton jButton_Examinar;
    private javax.swing.JButton jButton_Leer;
    private javax.swing.JComboBox<String> jComboBox_Puertos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Foto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_A;
    private javax.swing.JRadioButton jRadioButton_B;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_Apellido;
    private javax.swing.JTextField jTextField_CUI;
    private javax.swing.JTextField jTextField_Celular;
    private javax.swing.JTextField jTextField_DNI;
    private javax.swing.JTextField jTextField_Escuela;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Tarjeta;
    // End of variables declaration//GEN-END:variables
}
