package modelo;
// Generated 23/12/2016 10:43:28 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Consumo generated by hbm2java
 */
public class Consumo  implements java.io.Serializable {


     private ConsumoId id;
     private Estudiante estudiante;
     private Date fecha;
     private String comida;

    public Consumo() {
    }

    public Consumo(ConsumoId id, Estudiante estudiante, Date fecha, String comida) {
       this.id = id;
       this.estudiante = estudiante;
       this.fecha = fecha;
       this.comida = comida;
    }
   
    public ConsumoId getId() {
        return this.id;
    }
    
    public void setId(ConsumoId id) {
        this.id = id;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getComida() {
        return this.comida;
    }
    
    public void setComida(String comida) {
        this.comida = comida;
    }




}


