package modelo;
// Generated 23/12/2016 10:43:28 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private String tarjeta;
     private String nombre;
     private String apellido;
     private String dni;
     private String cui;
     private String escuela;
     private String celular;
     private byte[] foto;
     private Set pagos = new HashSet(0);
     private Set consumos = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(String tarjeta, String dni, String cui, String escuela) {
        this.tarjeta = tarjeta;
        this.dni = dni;
        this.cui = cui;
        this.escuela = escuela;
    }
    public Estudiante(String tarjeta, String nombre, String apellido, String dni, String cui, String escuela, String celular, byte[] foto, Set pagos, Set consumos) {
       this.tarjeta = tarjeta;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.cui = cui;
       this.escuela = escuela;
       this.celular = celular;
       this.foto = foto;
       this.pagos = pagos;
       this.consumos = consumos;
    }
   
    public String getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(String tarjeta) {
        this.tarjeta = tarjeta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getCui() {
        return this.cui;
    }
    
    public void setCui(String cui) {
        this.cui = cui;
    }
    public String getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(String escuela) {
        this.escuela = escuela;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }
    public Set getConsumos() {
        return this.consumos;
    }
    
    public void setConsumos(Set consumos) {
        this.consumos = consumos;
    }




}


