package modelo;
// Generated 23/12/2016 10:43:28 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private PagoId id;
     private Estudiante estudiante;
     private Date fecha;
     private double dinero;

    public Pago() {
    }

    public Pago(PagoId id, Estudiante estudiante, Date fecha, double dinero) {
       this.id = id;
       this.estudiante = estudiante;
       this.fecha = fecha;
       this.dinero = dinero;
    }
   
    public PagoId getId() {
        return this.id;
    }
    
    public void setId(PagoId id) {
        this.id = id;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getDinero() {
        return this.dinero;
    }
    
    public void setDinero(double dinero) {
        this.dinero = dinero;
    }




}


